## Matrix Computation ##

In [2]:
import numpy as np

**Problem 1**

Multiply the following matrices

In [4]:
# Create the matrices using Numpy arrays

A= np.array([[2,-14,8],[2,5,3]])
print(A)
print(A.shape)

B = np. array([[8,5,1],[6,10,-3]])
print(B)
print(B.shape)

[[  2 -14   8]
 [  2   5   3]]
(2, 3)
[[ 8  5  1]
 [ 6 10 -3]]
(2, 3)


In [13]:
# Compute the required operation (Multiplication) piecewise and print solution

sol = A.__mul__(B)
print(sol)

[[ 16 -70   8]
 [ 12  50  -9]]


In [15]:
#Multiply matrices using Transpose Operation

BT = np.transpose(B)
print(A)
print(BT)

sol2 = A.__matmul__(BT)
print(sol2)

[[  2 -14   8]
 [  2   5   3]]
[[ 8  6]
 [ 5 10]
 [ 1 -3]]
[[ -46 -152]
 [  44   53]]


### Problem 2 



In [21]:
#The Scalar product of a constant and matrix
lambda_value = -2
C = np.array([[-5,2,4],[6,10,-3],[-12,7,-2]])
print(lambda_value)
print(C)

scalar_product = lambda_value*C
print(scalar_product)

-2
[[ -5   2   4]
 [  6  10  -3]
 [-12   7  -2]]
[[ 10  -4  -8]
 [-12 -20   6]
 [ 24 -14   4]]


### Problem 3

Find the determinant of the following matrices


In [16]:
#Define the matrices

E = np.array([[2,-14,8],[2,5,3],[5,10,6]])
print(E)

F = np.array([[8,5,7,9],[-2,12,6,6],[7,15,2,3],[5,-7,1,4]])
print(F)



[[  2 -14   8]
 [  2   5   3]
 [  5  10   6]]
[[ 8  5  7  9]
 [-2 12  6  6]
 [ 7 15  2  3]
 [ 5 -7  1  4]]


In [17]:
# Find the determinant

det_E = np.linalg.det(E)
print(det_E)
det_F = np.linalg.det(F)
print(det_F)

-81.99999999999994
-2026.0
