In [1]:
import numpy as np

### Problem 1

12x + 3y = 162

8x + 3y = 122

In [11]:
# Create the matrices using Numpy arrays 

a = np.array([[12,3],[8,3]])
b = np.array([[162],[122]])


In [12]:
#Verify the size of the matrices and right hand-side vector

print('dim. of matrix a=', a.shape)
print('dim. of right hand vector b=', b.shape)

dim. of matrix a= (2, 2)
dim. of right hand vector b= (2, 1)


In [14]:
# Verify that a is invertible using its determinant

np.linalg.det(a)

#Inverse of the Matrix 

inv_a = np.linalg.inv(a)
print(inv_a)

[[ 0.25       -0.25      ]
 [-0.66666667  1.        ]]


In [15]:
# Solve the system using the method "dot"

sol = inv_a.dot(b)
print(sol)


[[10.]
 [14.]]


In [20]:
#Confirm answer

12*10 + 3*14 


162

In [21]:
#Confirm answer

8*10 + 3*14

122

### Problem 2

x + y = 6

6x + 3y = 30

In [23]:
# Create the matrices using Numpy arrays 

c = np.array([[1,1],[6,3]])
d = np.array([[6],[30]])

In [24]:
#Verify the size of the matrices and right hand-side vector

print('dim of matrix c =', c.shape)
print('dim of vector d =', d.shape)

dim of matrix c = (2, 2)
dim of vector d = (2, 1)


In [27]:
# Verify that a is invertible using its determinant

np.linalg.det(c)

#Inverse of the Matrix

inv_c = np.linalg.inv(c)
print(inv_c)


[[-1.          0.33333333]
 [ 2.         -0.33333333]]


In [28]:
# Solve the system using the method "dot"

sol2 = inv_c.dot(d)
print(sol2)

[[4.]
 [2.]]


### Problem 3

x + y + z = 12,000

-y + z = 4,000

0.03x + 0.04y + 0.07z = 670

In [37]:
# Create the matrices using Numpy arrays 

e = np.array([[1,1,1],[0,-1,2],[0.03,0.04,0.07]])
f = np.array([[12000],[4000],[670]])

In [38]:
#Verify the size of the matrices and right hand-side vector

print('Dim of matrix e =', e.shape)
print('Dim of vector f =', f.shape)

Dim of matrix e = (3, 3)
Dim of vector f = (3, 1)


In [42]:
# Verify that a is invertible using its determinant

np.linalg.det(e)

#Inverse of the Matrix

inv_e = np.linalg.inv(e)
print(inv_e)


[[  2.5          0.5        -50.        ]
 [ -1.          -0.66666667  33.33333333]
 [ -0.5          0.16666667  16.66666667]]


In [43]:
# Solve the system using the method "dot"

sol3 = inv_e.dot(f)
print(sol3)

[[-1500.        ]
 [ 7666.66666667]
 [ 5833.33333333]]


In [48]:
#Confirm Answer

-1500 + 7666.66666667 + 5833.33333333

(0.03*-1500) + (0.04*7666.66666667) + (0.07*5833.33333333)

669.9999999999001